local t = Def.ActorFrame {};

t[#t+1] = LoadFont("ScreenSystemLayer credits normal")..{
	InitCommand=cmd(x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y-10);
	OnCommand=function(self)
		self:settextf("WARNING\n\nTHIS GAME IS FOR SALE AND\nUSE IN JAPAN ONLY.\nTHE COPYRIGHTED\nMUSIC/CHARACTERS/ARTWORK\nIN THIS GAME ARE\nSEPARATELY OWNED BY THE AUTHORS.\nTHE PUBLIC PERFORMANCE\nOF THIS GAME\nOUTSIDE THIS TERRITORY IS\nPROHIBITED BY LAW AND\nVIOLATORS ARE SUBJECT TO\nSEVERE PENALTIES UNLESS\nSPECIALLY AUTHORIZED BY KONAMI\n\n\n(c)1999 KONAMI\n\nALL RIGHTS RESERVED.");
	end;
};

return t